-- 
-- Corrective Patch: Update News content with real long-form articles
--

UPDATE News 
SET content = '<h2>Celebrating the SUNY Class of 2026</h2><p>Today, SUNY University proudly celebrated the commencement of the Class of 2026. This year’s ceremony was a poignant reminder of resilience, academic rigor, and the spirit of innovation that defines our student body.</p><p>The ceremony, held on the Main Quad, honored students across all colleges, from the College of Engineering to the School of Performing Arts. As President Miller noted in her address, "You are graduating into a world that demands more than just knowledge; it demands the ability to apply that knowledge ethically, creatively, and with compassion for the communities you serve."</p><p>This cohort faced unprecedented challenges during their academic careers, yet they have distinguished themselves through high levels of scholarly output, participation in national research competitions, and community engagement. Over 40% of the graduating class completed independent research projects, and nearly every student participated in at least one professional internship program.</p><p>Among the graduates is an impressive array of talent. We have students moving on to top-tier PhD programs at Ivy League institutions, graduates securing roles in Fortune 500 companies, and others launching startups based on their senior capstone projects. The degree you hold today is not merely a piece of parchment; it is a testament to the thousands of hours you have poured into your studies, your late nights in the lab, your thoughtful critiques in the seminar room, and the deep friendships you have forged on this campus.</p><p>As you transition from students to alumni, remember that SUNY University remains your home. We look forward to seeing the incredible impact you will undoubtedly make in your respective fields. Congratulations to the Class of 2026—you have truly shaped the future.</p>' 
WHERE title = 'Fall Semester Commencement';

UPDATE News 
SET content = '<h2>Advancing Knowledge: The 2026 Annual Research Symposium</h2><p>The spirit of inquiry was alive and well this week as SUNY University hosted its Annual Research Symposium. This signature event brought together students, faculty, and industry partners to explore the breadth of groundbreaking work happening across our laboratories, studios, and academic departments.</p><p>The symposium showcased over 150 presentations, covering a wide array of topics. From the ethical implications of Large Language Models in healthcare, presented by the Department of Mathematics & Computer Science, to innovative sociological research on sustainable urban design, the caliber of work was nothing short of remarkable. The event highlighted the university’s interdisciplinary mission, as students from distinct fields collaborated to address complex real-world problems.</p><p>One of the highlights of this year’s symposium was the focus on community-impact research. Several research teams demonstrated how their technical findings could directly improve local services, such as enhancing energy grid efficiency for regional neighborhoods. Faculty mentor Professor Sarah Jenkins noted, "The goal of SUNY research is never just to publish; it is to produce work that matters. Seeing our students defend their findings with such rigor and passion is the ultimate proof that we are achieving that goal."</p><p>The symposium also facilitated invaluable networking opportunities. Representatives from regional biotech firms, governmental agencies, and cultural organizations were on-site to review student work, with many offering potential internships and career opportunities on the spot. The day concluded with an awards ceremony recognizing the most innovative projects in each discipline. We are already looking forward to next year, as the projects introduced today move into their next phases of development, promise, and public impact.</p>' 
WHERE title = 'Annual Research Symposium';

-- If 'SUNY Innovation Rank' exists, update it:
UPDATE News 
SET content = '<h2>SUNY Innovation Rank: A Look Behind the Numbers</h2><p>We are proud to announce that SUNY University has been ranked in the top 50 for Innovation. This ranking is a reflection of our commitment to fostering an environment where curiosity meets rigorous academic pursuit.</p><p>Innovation at SUNY is not just a buzzword; it is a fundamental pillar of our institutional strategy. We have invested heavily in interdisciplinary research hubs, created new paths for student-faculty collaboration, and established partnerships that bridge the gap between theoretical knowledge and practical application. By encouraging students to think outside the box and supporting faculty with state-of-the-art facilities, we have created an ecosystem that rewards bold ideas and sustainable development.</p><p>This ranking also underscores our success in technology transfer, where our academic discoveries are being successfully commercialized to solve pressing global challenges. Our students are graduating with the tools they need to lead in a rapidly changing economy, and our faculty members are actively shaping the future of their fields. This is not the end of our journey; it is a catalyst for even more ambitious projects as we continue to push the boundaries of what is possible.</p>' 
WHERE title = 'SUNY Innovation Rank';

-- If 'New AI Center' exists, update it:
UPDATE News 
SET content = '<h2>The New Frontier: AI Research Center</h2><p>The university is thrilled to unveil the new AI Research Center, a multi-million dollar facility dedicated to ethical AI development and interdisciplinary collaboration across all departments.</p><p>The center will serve as the hub for advanced machine learning research, focusing on the social, economic, and technical dimensions of artificial intelligence. It will host workshops, research fellowships, and partnerships with leading industry firms. The center’s primary focus is not only on technical prowess but also on understanding the human impact of AI, ensuring that our research aligns with the highest standards of safety, ethics, and inclusivity.</p><p>The facility is equipped with state-of-the-art high-performance computing resources, allowing our research teams to tackle data-intensive problems that were previously beyond reach. We anticipate that this center will become a magnet for top-tier talent in the field of AI, providing students with unrivaled research opportunities. As we prepare for the official opening this fall, we invite the entire SUNY community to engage with this center, whether through research, study, or interdisciplinary collaboration. The future of AI is being defined right here at SUNY.</p>' 
WHERE title = 'New AI Center';
